projectDbLocation: resources\projectDb.yaml
applicationDbLocation: resources\applicationDb.yaml
defaultKeyWord: launch
applicationKeyWord: application
projectKeyWord: project
executeKeyWord: execute
debugAlwaysOn: True
projectFileName: .kveikja
